<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>PINP Is Not Pastebin v0.0.1 - About</title>
        <link rel="stylesheet" type="text/css" href="style.css" media="screen" />
    </head>
    <body>
        <div id="header">
            <div id="logo">
                <h1>About PINP Is Not Pastebin v0.0.1</h1>
                <p>By <a href="http://www.frostedweb.com/">Frosted Web</a></p>
            </div>
            <!-- end #logo -->
            <div id="menu">
                <ul>
                    <li><a href="index.php">Home</a></li>
                    <li class="active"><a href="about.php">About PINP</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </div>
            <!-- end #menu -->
        </div>
        <!-- end #header -->
        <div id="page">
            <div id="content">
                <div class="post">
                    <h1 class="title">Welcome to PINPv0.0.1 </h1>
                    <p class="byline"><small>Posted by Frosted Web</small></p>
                    <div class="entry">
                        <p><strong>PINP </strong> is a pastebin from <a href="http://www.frostedweb.com/">Frosted Web</a>. Enjoy :)</p>
                    </div>
                    <div class="meta">
                        <p class="links">------------------------------------------------------------------------------------</p>
                    </div>
                </div>
                <div class="post">
                    <h2 class="title">What is PINP?</h2>
                    <p class="byline"><small>by Frosted Web.</small></p>
                    <div class="entry">
                        <p>PINPv0.0.1</p>
                        <p></p>
                    </div>
                    <div class="meta">
                        <p class="links"></p>
                    </div>
                </div>
            </div>
            <!-- end #content -->
            <div id="sidebar">
                <div id="sidebar-bgtop"></div>
                <div id="sidebar-content">
                    <ul>
                        <li>
                            <h2>Links</h2>
                            <ul>
                                <li><a href="http://www.frostedweb.com">Frosted Web</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div id="sidebar-bgbtm"></div>
            </div>
            <!-- end #sidebar -->
        </div>
        <!-- end #page -->
        <div id="footer">
            <p>Frosted Web &copy; 2009. All Rights Reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
        </div>
        <!-- end #footer -->
    </body>
</html>
