<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>PINP Is Not Pastebin v0.0.1 - Home</title>
        <link rel="stylesheet" type="text/css" href="assets/css/pinp.css" media="screen" />
        <script src="http://www.google.com/jsapi?key=ABQIAAAA1XbMiDxx_BTCY2_FkPh06RRaGTYH6UMl8mADNa0YKuWNNa8VNxQEerTAUcfkyrr6OwBovxn7TDAH5Q"></script>
        <script type="text/javascript">
            google.load("jquery", "1.3.2");
        </script>
    </head>
    <body>
        <div id="header">
            <div id="logo">
                <h1>PINP Is Not Pastebin v0.0.1</h1>
                <span class="tagline">Slap a code!</span>
            </div>
            <!-- end #logo -->
            <div id="menu">
                <ul>
                    <li class="active"><a href="pinp/index">Home</a></li>
                    <li><a href="pinp/about">About PINP</a></li>
                    <li><a href="#">Sign Up</a></li>
                </ul>
            </div>
            <!-- end #menu -->
        </div>
        <!-- end #header -->
        <?php
        //$self = $_SERVER["PHP_SELF"]."?";
        require(TALIESIN_LIB . "/geshi/geshi.php");
        require(TALIESIN_LIB . "/RedBean/redbean.inc.php");
        $toolbox = RedBean_Setup::kickstartDev("mysql:host=localhost;dbname=pinp","root","t3st1ng");
        $r = $toolbox->getRedBean();
        ?>
        <div id="page">
            <div id="content">
                <?php
                $adapter = $toolbox->getDatabaseAdapter();

                $posts = $adapter->get("select * from posts inner join users on posts.uid = users.uid");

                $pcount = count($posts);

                foreach($posts as $p): ?>
                <div class="post">
                    <div class="entry">
                        <p class="notes">notes:<br /><?=$p['notes']?></p>
                            <?php
                            $styles = "background:#777777;";
                            $headercontent = "Language: {LANGUAGE}";
                            $footercontent = " {TIME} sec. to highlight. | {SPEED} processed.";
                            $geshi = new GeSHi(stripslashes($p['code']), $p['code_type']);
                            $geshi->set_header_type(GESHI_HEADER_DIV);
                            $geshi->enable_line_numbers(GESHI_FANCY_LINE_NUMBERS, 2);
                            $geshi->set_line_style('background: #f8f8f8;', 'background: #f0f0f0;', true);
                            $geshi->set_header_content($headercontent);
                            $geshi->set_header_content_style($styles);
                            $geshi->set_footer_content($footercontent);
                            $geshi->set_footer_content_style($styles);
                            $code = $geshi->parse_code();
                            ?>
                        <div id="code">
                                <?=$code?>
                        </div>
                        <span>                           
                            <a href="<?=$self?>type=editpage&uid=<?= $p["uid"]; ?>&pid=<?= $p["pid"]; ?>">edit</a>
                            | <a href="<?=$self?>type=delpage&uid=<?= $p["uid"]; ?>&pid=<?= $p["pid"]; ?>">delete</a>
                        </span>
                        &nbsp;
                        <span class="byline"><small>Author: <?=$p['uname']?> | Posted: <?=$p['created']?></small></span>
                    </div>
                    <div class="meta">
                        <p class="links"></p>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
            <!-- end #content -->
            <div id="sidebar">
                <div id="sidebar-bgtop"></div>
                <div id="sidebar-content">
                    <div id="popupContact">
                        <a id="popupContactClose">close</a>
                        <h2>New</h2>
                        <p id="contactArea">
                            <?php
                            if(isset($_GET["type"]) && $_GET["type"]=="editpage") {
                                $page = $r->load("page",$_GET["id"]);
                            } else {
                                ?>
                            <form action="<?=$self?>type=savepage&id=<?=$_GET["id"]; ?>&pid=<?=$_GET["pid"]; ?>" method="post">
                                <fieldset>
                                    <label>Title: </label>
                                    <br />
                                    <input type="text" name="title" value="<?= $page->title; ?>" />
                                    <br />
                                    <label>Type of Syntax: </label>
                                    <br />
                                    <select name="<?= $page->syntax_type; ?>">
                                        <optgroup label="Syntax">
                                            <option value="text">Text</option>
                                            <option value="php">PHP</option>
                                            <option value="html">HTML</option>
                                            <option value="css">CSS</option>
                                            <option value="javascript">Javascript</option>
                                            <option value="perl">Perl</option>
                                            <option value="python">Python</option>
                                        </optgroup>
                                    </select>
                                    <br />
                                    <label>Notes: </label>
                                    <br />
                                    <textarea name="intro" ><?= $page->intro; ?></textarea>
                                    <br />
                                    <label>Code: </label>
                                    <br />
                                    <textarea name="body" ><?= $page->body; ?></textarea>
                                    <input type="submit" name="save" value="save" />
                                </fieldset>
                            </form>
                                <?php

                                if(isset($_GET["type"]) && $_GET["type"]=="savepage") {
                                    $page = $r->load( "post", max($_GET["pid"],1));
                                    $post = $r->load("post", $_GET["id"] );
                                    $post->import($_POST, "title,intro,body,syntax_type");
                                    $r->store($post);
                                    $tree = new RedBean_TreeManager( $toolbox );
                                    $tree->attach( $page, $post );
                                } else {
                                    if(isset($_GET["type"]) && $_GET["type"]=="delpage") {
                                        $adapter->exec("delete from posts where pid =\"" . $_GET["pid"] ."\"" );
                                    }
                                }
                            }
                            ?>
                        </p>
                    </div>
                    <div id="backgroundPopup"></div>

                    <?php
                    @$currentparent = $r->load("post",(max($_GET["pid"],1)));
                    $tree = new RedBean_TreeManager( $toolbox );
                    $posts = $tree->children( $currentparent );
                    ?>
                    <ul id="sidemenu">
                        <li>
                            <ul>
                                <li><a id="button">add new code clip</a></li>
                            </ul>
                        </li>
                        <li>
                            <ul>
                                <li><a href="http://www.frostedweb.com">Frosted Web</a></li>
                            </ul>
                        </li>
                </div>
                <div id="sidebar-bgbtm"></div>
            </div>
            <!-- end #sidebar -->
        </div>
        <!-- end #page -->
        <div id="footer">
            <p>
                PINP v0.0.1 by Frosted Web &copy; 2009. All Rights Reserved.<br />
                Postings are copyrighted to their respective owners. To report abuse of the site please follow the report link.</p>
            </p>
        </div>
        <!-- end #footer -->
    </body>
</html>